((scheme-mode
  (indent-tabs-mode . nil)
  (lisp-local-indent
   ^ 1
   and-let* 1
   begin0 0
   call-with-client-socket 1
   call-with-input-conversion 1
   call-with-input-file 1
   call-with-input-process 1
   call-with-input-string 1
   call-with-iterator 1
   call-with-output-conversion 1
   call-with-output-file 1
   call-with-output-string 0
   call-with-temporary-file 1
   call-with-values 1
   dolist 1
   dotimes 1
   if 1
   if-match 2
   let*-values 1
   let-args 2
   let-keywords* 2
   let-match 2
   let-optionals* 2
   let-syntax 1
   let-values 1
   let/cc 1
   let1 2
   letrec-syntax 1
   make 1
   multiple-value-bind 2
   parameterize 1
   parse-options 1
   receive 2
   rxmatch-case 1
   rxmatch-cond 0
   rxmatch-if  2
   rxmatch-let 2
   syntax-rules 1
   unless 1
   until 1
   when 1
   while 1
   with-builder 1
   with-error-handler 0
   with-error-to-port 1
   with-input-conversion 1
   with-input-from-port 1
   with-input-from-process 1
   with-input-from-string 1
   with-iterator 1
   with-module 1
   with-output-conversion 1
   with-output-to-port 1
   with-output-to-process 1
   with-output-to-string 0
   with-port-locking 1
   with-signal-handlers 1
   with-string-io 1
   with-time-counter 1)))
