((scheme-mode
  (indent-tabs-mode . nil)
  (lisp-local-indent
   ^ 1
   $let 1
   $let* 1
   and-let* 1
   and-let1 2
   begin0 0
   call-with-client-socket 1
   call-with-input-conversion 1
   call-with-input-file 1
   call-with-input-process 1
   call-with-input-string 1
   call-with-iterator 1
   call-with-output-conversion 1
   call-with-output-file 1
   call-with-output-string 0
   call-with-process-io 1
   call-with-string-io 1
   call-with-temporary-file 1
   call-with-values 1
   define-method 2
   do-generator 1
   dolist 1
   dotimes 1
   ecase 1
   eval-when 1
   glet* 1
   glet1 2
   guard 1
   if 1
   if-let1 2
   if-match 2
   let*-values 1
   let-args 2
   let-keywords 2
   let-keywords* 2
   let-match 2
   let-optionals* 2
   let-syntax 1
   let-values 1
   let/cc 1
   let1 2
   letrec-syntax 1
   make 1
   match 1
   match-lambda 0
   match-lambda* 0
   match-let 1
   match-let* 1
   match-let1 2
   match-letrec 1
   parameterize 1
   parse-options 1
   quasirename 1
   rec 1
   receive 2
   rlet1 2
   rxmatch-case 1
   rxmatch-cond 0
   rxmatch-if  2
   rxmatch-let 2
   syntax-rules 1
   unless 1
   until 1
   unwind-protect 1
   when 1
   while 1
   with-builder 1
   with-error-handler 0
   with-error-to-port 1
   with-input-conversion 1
   with-input-from-port 1
   with-input-from-process 1
   with-input-from-string 1
   with-iterator 1
   with-module 1
   with-output-conversion 1
   with-output-to-port 1
   with-output-to-process 1
   with-output-to-string 0
   with-port-locking 1
   with-ports 3
   with-signal-handlers 1
   with-string-io 1
   with-time-counter 1)))
