#! /bin/sh
autoconf
(cd gc; autoconf)
(cd libltdl; autoconf)
extensions=`grep '^SUBDIRS=' ext/Makefile.am | sed -e 's/SUBDIRS=//'`
for ext in $extensions; do (echo $ext; cd ext/$ext; autoconf -I ../..); done
