extern ScmObj size_of_int8();
extern ScmObj size_of_uint8();
extern ScmObj size_of_int16();
extern ScmObj size_of_uint16();
extern ScmObj size_of_int32();
extern ScmObj size_of_uint32();
extern ScmObj size_of_int64();
extern ScmObj size_of_uint64();
extern ScmObj size_of_char();
extern ScmObj size_of_unsigned_char();
extern ScmObj size_of_short();
extern ScmObj size_of_unsigned_short();
extern ScmObj size_of_int();
extern ScmObj size_of_unsigned_int();
extern ScmObj size_of_long();
extern ScmObj size_of_unsigned_long();
extern ScmObj size_of_float();
extern ScmObj size_of_double();
extern ScmObj size_of_string();
extern ScmObj size_of_pointer();

extern ScmObj align_of_int8();
extern ScmObj align_of_uint8();
extern ScmObj align_of_int16();
extern ScmObj align_of_uint16();
extern ScmObj align_of_int32();
extern ScmObj align_of_uint32();
extern ScmObj align_of_int64();
extern ScmObj align_of_uint64();
extern ScmObj align_of_char();
extern ScmObj align_of_unsigned_char();
extern ScmObj align_of_short();
extern ScmObj align_of_unsigned_short();
extern ScmObj align_of_int();
extern ScmObj align_of_unsigned_int();
extern ScmObj align_of_long();
extern ScmObj align_of_unsigned_long();
extern ScmObj align_of_float();
extern ScmObj align_of_double();
extern ScmObj align_of_string();
extern ScmObj align_of_pointer();

extern ScmObj internal_open_shared_library(ScmString* path, ScmString* version, ScmObj throw_error);
extern ScmObj close_shared_library(ScmObj shared_library);
extern ScmObj shared_object_suffix();
//extern ScmObj address(ScmObj pointer, int offset);
//extern ScmObj pointer_to_integer(ScmObj pointer);
//extern ScmObj pointer_to_uinteger(ScmObj pointer);
//extern ScmObj integer_to_pointer(intptr_t integer);
extern ScmObj allocate_pointer(int size);
extern ScmObj empty_pointer();
extern ScmObj is_null_pointer(ScmObj pointer);
extern ScmObj is_pointer(ScmObj pointer);
//extern ScmObj pointer_free(ScmObj pointer);


extern ScmObj pointer_set_c_int8(ScmObj pointer, int offset, int8_t value);
extern ScmObj pointer_set_c_uint8(ScmObj pointer, int offset, uint8_t value);
extern ScmObj pointer_set_c_int16(ScmObj pointer, int offset, int16_t value);
extern ScmObj pointer_set_c_uint16(ScmObj pointer, int offset, uint16_t value);
extern ScmObj pointer_set_c_int32(ScmObj pointer, int offset, int32_t value);
extern ScmObj pointer_set_c_uint32(ScmObj pointer, int offset, uint32_t value);
extern ScmObj pointer_set_c_int64(ScmObj pointer, int offset, int64_t value);
extern ScmObj pointer_set_c_uint64(ScmObj pointer, int offset, uint64_t value);
extern ScmObj pointer_set_c_char(ScmObj pointer, int offset, char value);
extern ScmObj pointer_set_c_unsigned_char(ScmObj pointer, int offset, unsigned char value);
extern ScmObj pointer_set_c_short(ScmObj pointer, int offset, short value);
extern ScmObj pointer_set_c_unsigned_short(ScmObj pointer, int offset, unsigned short value);
extern ScmObj pointer_set_c_int(ScmObj pointer, int offset, int value);
extern ScmObj pointer_set_c_unsigned_int(ScmObj pointer, int offset, unsigned int value);
extern ScmObj pointer_set_c_long(ScmObj pointer, int offset, long value);
extern ScmObj pointer_set_c_unsigned_long(ScmObj pointer, int offset, unsigned long value);
extern ScmObj pointer_set_c_float(ScmObj pointer, int offset, float value);
extern ScmObj pointer_set_c_double(ScmObj pointer, int offset, double value);
extern ScmObj pointer_set_c_pointer(ScmObj pointer, int offset, ScmObj value);

extern ScmObj pointer_ref_c_int8(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_uint8(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_int16(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_uint16(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_int32(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_uint32(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_int64(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_uint64(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_char(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_unsigned_char(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_short(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_unsigned_short(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_int(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_unsigned_int(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_long(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_unsigned_long(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_float(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_double(ScmObj pointer, int offset);
extern ScmObj pointer_ref_c_pointer(ScmObj pointer, int offset);

extern ScmObj string_to_pointer(ScmObj string);
extern ScmObj pointer_to_string(ScmObj pointer);

extern ScmObj internal_dlerror();
extern ScmObj internal_dlsym(ScmObj shared_object, ScmString* c_name);
extern ScmObj internal_ffi_call(ScmObj nargs, ScmObj rtype, ScmObj atypes, ScmObj fn, ScmObj rvalue, ScmObj avalues);
extern ScmObj scheme_procedure_to_pointer(ScmObj procedure);

extern ScmObj get_ffi_type_int8();
extern ScmObj get_ffi_type_uint8();
extern ScmObj get_ffi_type_int16();
extern ScmObj get_ffi_type_uint16();
extern ScmObj get_ffi_type_int32();
extern ScmObj get_ffi_type_uint32();
extern ScmObj get_ffi_type_int64();
extern ScmObj get_ffi_type_uint64();
extern ScmObj get_ffi_type_char();
extern ScmObj get_ffi_type_unsigned_char();
extern ScmObj get_ffi_type_short();
extern ScmObj get_ffi_type_unsigned_short();
extern ScmObj get_ffi_type_int();
extern ScmObj get_ffi_type_unsigned_int();
extern ScmObj get_ffi_type_long();
extern ScmObj get_ffi_type_unsigned_long();
extern ScmObj get_ffi_type_float();
extern ScmObj get_ffi_type_double();
extern ScmObj get_ffi_type_void();
extern ScmObj get_ffi_type_pointer();

extern void Scm_Init_gauche_ffi(void);

