\input texinfo  @c -*-texinfo-*-
@comment %**start of header
@c EN
@setfilename gauche-refe.info
@settitle Gauche Reference Manual
@dircategory The Algorithmic Language Scheme
@direntry
* Gauche Reference: (gauche-refe.info).	An R5RS Scheme implementation.
@end direntry
@c JP
@setfilename gauche-refj.info
@settitle Gauche リファレンスマニュアル
@dircategory The Algorithmic Language Scheme
@direntry
* Gauche Reference (ja): (gauche-refj.info).	An R5RS Scheme implementation.
@end direntry
@c COMMON
@comment %**end of header

@c $Id: gauche-ref.texi,v 1.425 2003-07-18 09:47:00 shirok Exp $

@c module and class index
@defcodeindex md
@defcodeindex cl

@iftex
@finalout
@parskip 4pt plus 1pt
@end iftex

@titlepage
@c EN
@title Gauche Reference Manual
@subtitle version @VERSION@
@author Shiro Kawai (shiro@@acm.org)
@c JP
@title Gauche リファレンスマニュアル
@subtitle version @VERSION@
@author Shiro Kawai (shiro@@acm.org)
@c COMMON

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2001-2003 Shiro Kawai (shiro@@acm.org)

@end titlepage

@node Top, Introduction, (dir), (dir)

@ifnottex
@c EN
This is a reference manual of Gauche, an R5RS Scheme implementation.
This manual is for version @VERSION@.
@c JP
本書は、R5RS準拠のScheme処理系、Gaucheのリファレンスマニュアルです。
Gaucheのバージョン@VERSION@に対応します。
@c COMMON
@end ifnottex

@menu
* Introduction::                
* Concepts::                    
* Programming in Gauche::       
* Core syntax::                 
* Macros::                      
* Core library::                
* Object system::               
* Library modules - Overview::  
* Library modules - Gauche extensions::  
* Library modules - SRFIs::     
* Library modules - Utilities::  
* References::                  
* C to Scheme mapping::         
* Indices::                     
@end menu

@include intro.texi
@include concepts.texi
@include program.texi
@include coresyn.texi
@include macro.texi
@include corelib.texi
@include object.texi
@include modintro.texi
@include modgauche.texi
@include modsrfi.texi
@include modutil.texi
@include references.texi
@include mapping.texi

@node Indices,  , C to Scheme mapping, Top
@appendix Indices
@c NODE 索引

@menu
* Function and Syntax Index::   
* Module Index::                
* Class Index::                 
* Variable Index::              
@end menu

@node Function and Syntax Index, Module Index, Indices, Indices
@appendixsec Function and Syntax Index
@c NODE 手続きと構文索引
@printindex fn

@node Module Index, Class Index, Function and Syntax Index, Indices
@appendixsec Module Index
@c NODE モジュール索引
@printindex md


@node Class Index, Variable Index, Module Index, Indices
@appendixsec Class Index
@c NODE クラス索引

For readability, the surrounding @code{<} and @code{>} are stripped off.

@printindex cl

@node Variable Index,  , Class Index, Indices
@appendixsec Variable Index
@c NODE 変数索引
@printindex vr


@contents
@bye

