#!/bin/sh
# Helper script to create "slibcat" before installing gosh.
# The caller must guarantee existence of slib.
# See "slibcat-in-place" target in the Makefile.
#
# Usage: mklibcat PATH-TO-GOSH

set -e

GOSH=$1

$GOSH -ftest -uslib  \
    -E'with-module slib (define (implementation-vicinity) "./")' \
    -E"require 'new-catalog" \
    -Eexit

