;;
;; Generate srfi-160 interface filtes
;;

(use file.util)

(define (usage)
  (print "Usage: gosh ./ifgen.scm TAG")
  (exit 1))

(define (main args)
  (unless (= (length args) 2) (usage))
  (do-it (cadr args))
  0)

(define (do-it tag)
  (with-output-to-file (format "uvector/~a.scm" tag)
    (^[]
      (print ";; Generated automatically.  Do not edit")
      (pprint `(define-module ,(symbol-append 'gauche.uvector. tag)
                 (use gauche.uvector)
                 (export ,(symbol-append 'make- tag 'vector)
                         ,(symbol-append tag 'vector)
                         ,(symbol-append tag 'vector-unfold)
                         ,(symbol-append tag 'vector-unfold-right)
                         ,(symbol-append tag 'vector-copy)
                         ,(symbol-append tag 'vector-reverse-copy)
                         ,(symbol-append tag 'vector-append)
                         ,(symbol-append tag 'vector-concatenate)
                         ,(symbol-append tag 'vector-append-subvectors)
                         ,(symbol-append tag '?)
                         ,(symbol-append tag 'vector?)
                         ,(symbol-append tag 'vector-empty?)
                         ,(symbol-append tag 'vector=)
                         ,(symbol-append tag 'vector-ref)
                         ,(symbol-append tag 'vector-length)
                         ,(symbol-append tag 'vector-take)
                         ,(symbol-append tag 'vector-take-right)
                         ,(symbol-append tag 'vector-drop)
                         ,(symbol-append tag 'vector-drop-right)
                         ,(symbol-append tag 'vector-segment)
                         ,(symbol-append tag 'vector-fold)
                         ,(symbol-append tag 'vector-fold-right)
                         ,(symbol-append tag 'vector-map)
                         ,(symbol-append tag 'vector-map!)
                         ,(symbol-append tag 'vector-for-each)
                         ,(symbol-append tag 'vector-count)
                         ,(symbol-append tag 'vecotr-cumulate)
                         ,(symbol-append tag 'vector-take-while)
                         ,(symbol-append tag 'vector-take-while-right)
                         ,(symbol-append tag 'vector-drop-while)
                         ,(symbol-append tag 'vector-drop-while-right)
                         ,(symbol-append tag 'vector-index)
                         ,(symbol-append tag 'vector-index-right)
                         ,(symbol-append tag 'vector-skip)
                         ,(symbol-append tag 'vector-skip-right)
                         ,(symbol-append tag 'vector-any)
                         ,(symbol-append tag 'vector-every)
                         ,(symbol-append tag 'vector-partition)
                         ,(symbol-append tag 'vector-filter)
                         ,(symbol-append tag 'vector-remove)
                         ,(symbol-append tag 'vector-set!)
                         ,(symbol-append tag 'vector-swap!)
                         ,(symbol-append tag 'vector-fill!)
                         ,(symbol-append tag 'vector-reverse!)
                         ,(symbol-append tag 'vector-copy!)
                         ,(symbol-append tag 'vector-reverse-copy!)
                         ,(symbol-append tag 'vector->list)
                         ,(symbol-append 'reverse- tag 'vector->list)
                         ,(symbol-append 'list-> tag 'vector)
                         ,(symbol-append tag 'vector->vector)
                         ,(symbol-append 'vector-> 'vector)
                         ,(symbol-append 'make- tag 'vector-generator)
                         ,(symbol-append 'write- tag 'vector)
                         ))))))
