#!/bin/sh
# Helper script to handle building libgauche.dylib on MacOSX
# Assumes $TARGETLIB is set by the caller.
CCLD=$1
shift
if echo "$*" | grep dynamiclib > /dev/null 2>&1 ; then
  $CCLD -install_name ${TARGETLIB}/libgauche.dylib "$@"
else
  $CCLD -L${TARGETLIB} "$@"
fi
