#!/bin/sh
# Helper script to create a symlink to sharedlib,
#   like libgauche.so -> libgauche.so.0.1
# Assumes $TARGETLIB is set by the caller.

LIBGAUCHE=$1

API_VERSION=`cat ../VERSION | sed 's/_.*//'`

oldifs=$IFS
IFS="."
set $API_VERSION
IFS=$oldifs

API_MAJOR_VERSION=$1
API_MINOR_VERSION=$2
API_MICRO_VERSION=$3

: ${API_MINOR_VERSION:=0}
: ${API_MICRO_VERSION:=0}

LIB_VVV=$LIBGAUCHE.$API_MAJOR_VERSION.$API_MINOR_VERSION.$API_MICRO_VERSION
LIB_V=$LIBGAUCHE.$API_MAJOR_VERSION

# avoid re-running mkverslink.
if test -f $TARGETLIB/$LIB_VVV -a -L $TARGETLIB/$LIBGAUCHE; then exit; fi

cd $TARGETLIB
rm -f $LIB_VVV
mv $LIBGAUCHE $LIB_VVV
ln -s $LIB_VVV $LIBGAUCHE
rm -f $LIB_V
ln -s $LIB_VVV $LIB_V

